@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global early_return
early_return:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #8
	str r0, [fp, #-4]   @ param x
	@ return
	ldr r0, [fp, #-4]   @ x
	b .Lret_early_return
.Lret_early_return:
	mov sp, fp
	pop {fp, pc}

.global always_true_branch
always_true_branch:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #8
	str r0, [fp, #-4]   @ param x
	@ return
	ldr r0, [fp, #-4]   @ x
	mov r1, #1
	add r0, r0, r1
	b .Lret_always_true_branch
.Lret_always_true_branch:
	mov sp, fp
	pop {fp, pc}

.global always_false_branch
always_false_branch:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #8
	str r0, [fp, #-4]   @ param x
	@ return
	ldr r0, [fp, #-4]   @ x
	b .Lret_always_false_branch
.Lret_always_false_branch:
	mov sp, fp
	pop {fp, pc}
