@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global code_hoisting
code_hoisting:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #16
	str r0, [fp, #-4]   @ param x
	@ decl base
	mov r0, #10
	str r0, [fp, #-8]   @ store base
	@ if
	ldr r0, [fp, #-4]   @ x
	mov r1, #0
	cmp r0, r1
	movgt r0, #1
	movle r0, #0
	cmp r0, #0
	beq .L0
	@ decl result
	ldr r0, [fp, #-8]   @ base
	ldr r1, [fp, #-4]   @ x
	add r0, r0, r1
	str r0, [fp, #-12]   @ store result
	@ return
	ldr r0, [fp, #-12]   @ result
	b .Lret_code_hoisting
	b .L1
.L0:
	@ decl result
	ldr r0, [fp, #-8]   @ base
	ldr r1, [fp, #-4]   @ x
	sub r0, r0, r1
	str r0, [fp, #-12]   @ store result
	@ return
	ldr r0, [fp, #-12]   @ result
	b .Lret_code_hoisting
.L1:
.Lret_code_hoisting:
	mov sp, fp
	pop {fp, pc}
