@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global strength_reduction
strength_reduction:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #40
	str r0, [fp, #-4]   @ param x
	@ decl a
	ldr r0, [fp, #-4]   @ x
	str r0, [fp, #-8]   @ store a
	@ decl b
	mov r0, #0
	str r0, [fp, #-12]   @ store b
	@ decl c
	ldr r0, [fp, #-4]   @ x
	str r0, [fp, #-16]   @ store c
	@ decl d
	ldr r0, [fp, #-4]   @ x
	str r0, [fp, #-20]   @ store d
	@ decl e
	ldr r0, [fp, #-4]   @ x
	str r0, [fp, #-24]   @ store e
	@ decl f
	mov r0, #0
	str r0, [fp, #-28]   @ store f
	@ decl g
	ldr r0, [fp, #-4]   @ x
	ldr r1, [fp, #-4]   @ x
	add r0, r0, r1
	str r0, [fp, #-32]   @ store g
	@ decl h
	ldr r0, [fp, #-4]   @ x
	ldr r1, [fp, #-4]   @ x
	add r0, r0, r1
	ldr r1, [fp, #-4]   @ x
	ldr r2, [fp, #-4]   @ x
	add r1, r1, r2
	add r0, r0, r1
	str r0, [fp, #-36]   @ store h
	@ return
	ldr r0, [fp, #-32]   @ g
	ldr r1, [fp, #-36]   @ h
	add r0, r0, r1
	b .Lret_strength_reduction
.Lret_strength_reduction:
	mov sp, fp
	pop {fp, pc}
