@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global constant_folding
constant_folding:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #24
	@ decl a
	mov r0, #5
	str r0, [fp, #-4]   @ store a
	@ decl b
	mov r0, #40
	str r0, [fp, #-8]   @ store b
	@ decl c
	mov r0, #42
	str r0, [fp, #-12]   @ store c
	@ decl d
	mov r0, #5
	str r0, [fp, #-16]   @ store d
	@ decl e
	mov r0, #11
	str r0, [fp, #-20]   @ store e
	@ return
	ldr r0, [fp, #-4]   @ a
	ldr r1, [fp, #-8]   @ b
	add r0, r0, r1
	ldr r1, [fp, #-12]   @ c
	add r0, r0, r1
	ldr r1, [fp, #-16]   @ d
	add r0, r0, r1
	ldr r1, [fp, #-20]   @ e
	add r0, r0, r1
	b .Lret_constant_folding
.Lret_constant_folding:
	mov sp, fp
	pop {fp, pc}
