@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global main
main:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #8
	@ expr stmt
	mov r0, #5
	@ return
	@ WARNING: 'global_a' not found in frame
	b .Lret_main
.Lret_main:
	mov sp, fp
	pop {fp, pc}
