@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global func1
func1:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #16
	str r0, [fp, #-4]   @ param a
	str r1, [fp, #-8]   @ param b
	@ expr stmt
	ldr r0, [fp, #-4]   @ a
	ldr r1, [fp, #-8]   @ b
	add r0, r0, r1
	str r0, [fp, #-12]   @ c =
	@ return
	ldr r0, [fp, #-12]   @ c
	b .Lret_func1
.Lret_func1:
	mov sp, fp
	pop {fp, pc}
