@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global main
main:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #16
	str r0, [fp, #-4]   @ param c
	@ decl d
	mov r0, #2
	str r0, [fp, #-8]   @ store d
	@ decl c
	mov r0, #4
	str r0, [fp, #-4]   @ store c
	@ expr stmt
	ldr r0, [fp, #-4]   @ c
	ldr r1, [fp, #-8]   @ d
	add r0, r0, r1
	str r0, [fp, #-12]   @ ans =
	@ return
	mov r0, #0
	b .Lret_main
.Lret_main:
	mov sp, fp
	pop {fp, pc}
