@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text
	@ decl GLOBAL_CHAR
	mov r0, #109
	str r0, [fp, #-4]   @ store GLOBAL_CHAR

.global main
main:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #24
	@ decl number
	mov r0, #300
	str r0, [fp, #-4]   @ store number
	@ decl decimal
	@ unsupported expr kind 15
	str r0, [fp, #-8]   @ store decimal
	@ decl character
	mov r0, #116
	str r0, [fp, #-12]   @ store character
	@ decl boolean
	mov r0, #1
	str r0, [fp, #-16]   @ store boolean
	@ if
	ldr r0, [fp, #-4]   @ number
	ldr r1, [fp, #-12]   @ character
	cmp r0, r1
	movne r0, #1
	moveq r0, #0
	cmp r0, #0
	beq .L0
	@ expr stmt
	ldr r0, [fp, #-4]   @ number
	mov r1, #300
	add r0, r0, r1
	str r0, [fp, #-4]   @ number =
	@ expr stmt
	ldr r0, [fp, #-4]   @ number
	ldr r1, [fp, #-8]   @ decimal
	mov r2, #100
	mul r1, r2, r1
	sub r0, r0, r1
	str r0, [fp, #-8]   @ decimal =
	@ if
	ldr r0, [fp, #-4]   @ number
	ldr r1, [fp, #-8]   @ decimal
	cmp r0, r1
	movgt r0, #1
	movle r0, #0
	cmp r0, #0
	beq .L2
	@ expr stmt
	mov r0, #116
	@ expr stmt
	ldr r0, [fp, #-8]   @ decimal
	mov r1, #100
	sdiv r0, r0, r1
	str r0, [fp, #-4]   @ number =
	b .L3
.L2:
	@ decl flt
	@ unsupported expr kind 15
	str r0, [fp, #-20]   @ store flt
	@ expr stmt
	ldr r0, [fp, #-8]   @ decimal
	ldr r1, [fp, #-4]   @ number
	mov r2, #100
	mul r1, r2, r1
	@ unsupported expr kind 15
	mul r1, r2, r1
	add r0, r0, r1
	str r0, [fp, #-4]   @ number =
.L3:
	b .L1
.L0:
.L1:
.Lret_main:
	mov sp, fp
	pop {fp, pc}
