@ ARM32 Assembly  (generated by code_gen)
.arch armv7-a
.text

.global main
main:
	push {fp, lr}
	mov fp, sp
	sub sp, sp, #8
	@ decl a
	@ unsupported expr kind 15
	str r0, [fp, #-4]   @ store a
	@ decl b
	@ unsupported expr kind 15
	str r0, [fp, #-8]   @ store b
	@ if
	ldr r0, [fp, #-4]   @ a
	ldr r1, [fp, #-8]   @ b
	cmp r0, r1
	moveq r0, #1
	movne r0, #0
	cmp r0, #0
	beq .L0
	@ return
	ldr r0, [fp, #-4]   @ a
	ldr r1, [fp, #-8]   @ b
	add r0, r0, r1
	b .Lret_main
	b .L1
.L0:
	@ return
	mov r0, #0
	b .Lret_main
.L1:
.Lret_main:
	mov sp, fp
	pop {fp, pc}
